// flow-typed signature: ae53aaae83b529bc8501095d85ce2aee
// flow-typed version: <<STUB>>/flat-cache_v^1.3.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flat-cache'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'flat-cache' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'flat-cache/cache' {
  declare module.exports: any;
}

declare module 'flat-cache/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'flat-cache/cache.js' {
  declare module.exports: $Exports<'flat-cache/cache'>;
}
declare module 'flat-cache/utils.js' {
  declare module.exports: $Exports<'flat-cache/utils'>;
}
