// flow-typed signature: f2449821c981d8e4080177afb936f61c
// flow-typed version: <<STUB>>/is-online_v^7.0.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'is-online'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'is-online' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'is-online/browser' {
  declare module.exports: any;
}

// Filename aliases
declare module 'is-online/browser.js' {
  declare module.exports: $Exports<'is-online/browser'>;
}
declare module 'is-online/index' {
  declare module.exports: $Exports<'is-online'>;
}
declare module 'is-online/index.js' {
  declare module.exports: $Exports<'is-online'>;
}
