// flow-typed signature: c5f5c9bc1d8a0864c837583250a7fa25
// flow-typed version: <<STUB>>/npm-logical-tree_v^1.2.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'npm-logical-tree'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'npm-logical-tree' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'npm-logical-tree/index' {
  declare module.exports: $Exports<'npm-logical-tree'>;
}
declare module 'npm-logical-tree/index.js' {
  declare module.exports: $Exports<'npm-logical-tree'>;
}
